### ISSUE TITLE
Naive query for certified but not otherwise ingested artifacts may fail.

### ISSUE THREAD

**Issue by bobmcwhirter** [guacsec/guac#1001]
**Describe the bug**

Certifying (poorly) an artifact that is otherwise unknown works, but querying the artifacts then fails. At least the naive way I did it.

**To Reproduce**

` ./bin/guacone certify -g artifact "approved by bob" 'pkg:rpm/redhat/acl@2.2.51-15.el7?arch=ppc64le'`

Then query `{ artifacts { id } }`

**Expected behavior**

Not a nil pointer.

**Screenshots**
```
runtime error: invalid memory address or nil pointer dereference

goroutine 827 [running]:
runtime/debug.Stack()
	/usr/local/Cellar/go/1.19.1/libexec/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
	/usr/local/Cellar/go/1.19.1/libexec/src/runtime/debug/stack.go:16 +0x1c
github.com/99designs/gqlgen/graphql.DefaultRecover({0x103760fa0?, 0x1400062e360?}, {0x103695ae0?, 0x103bc2100?})
	/Users/bob/go/pkg/mod/github.com/99designs/gqlgen@v0.17.34/graphql/recovery.go:17 +0x78
github.com/99designs/gqlgen/graphql.(*OperationContext).Recover(0x14000012528?, {0x103760fa0, 0x1400057e510}, {0x103695ae0?, 0x103bc2100?})
	/Users/bob/go/pkg/mod/github.com/99designs/gqlgen@v0.17.34/graphql/context_operation.go:124 +0x44
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query_artifacts.func1()
	/Users/bob/repos/trustification/guac/pkg/assembler/graphql/generated/artifact.generated.go:2590 +0x68
panic({0x103695ae0, 0x103bc2100})
	/usr/local/Cellar/go/1.19.1/libexec/src/runtime/panic.go:884 +0x204
github.com/guacsec/guac/pkg/assembler/backends/inmem.(*demoClient).artifactExact(0x2000?, 0x0)
	/Users/bob/repos/trustification/guac/pkg/assembler/backends/inmem/artifact.go:128 +0x20
github.com/guacsec/guac/pkg/assembler/backends/inmem.(*demoClient).Artifacts(0x140002188c0, {0x20?, 0x14000012938?}, 0x0)
	/Users/bob/repos/trustification/guac/pkg/assembler/backends/inmem/artifact.go:161 +0xc8
github.com/guacsec/guac/pkg/assembler/graphql/resolvers.(*queryResolver).Artifacts(0x10368fa00?, {0x103760fa0?, 0x1400057e510?}, 0xc?)
	/Users/bob/repos/trustification/guac/pkg/assembler/graphql/resolvers/artifact.resolvers.go:21 +0x38
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query_artifacts.func2({0x103760fa0?, 0x1400057e510})
	/Users/bob/repos/trustification/guac/pkg/assembler/graphql/generated/artifact.generated.go:2596 +0xd0
github.com/99designs/gqlgen/graphql/executor.processExtensions.func4({0x103760fa0?, 0x1400057e510?}, 0x14000696460?)
	/Users/bob/go/pkg/mod/github.com/99designs/gqlgen@v0.17.34/graphql/executor/extensions.go:72 +0x2c
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query_artifacts(0x1400006c140, {0x103760fa0, 0x1400057e450}, {0x1400051f780, {0x14000328610, 0x1, 0x1}, 0x0})
	/Users/bob/repos/trustification/guac/pkg/assembler/graphql/generated/artifact.generated.go:2594 +0x1dc
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query.func1({0x103760fa0?, 0x1400057e450?}, 0x1400029e190)
	/Users/bob/repos/trustification/guac/pkg/assembler/graphql/generated/artifact.generated.go:4677 +0x94
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query.func2.1({0x103760fa0?, 0x1400057e450?})
	/Users/bob/repos/trustification/guac/pkg/assembler/graphql/generated/artifact.generated.go:4686 +0x30
github.com/99designs/gqlgen/graphql/executor.processExtensions.func3({0x103760fa0?, 0x1400057e450?}, 0x103eccf18?)
	/Users/bob/go/pkg/mod/github.com/99designs/gqlgen@v0.17.34/graphql/executor/extensions.go:69 +0x2c
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query.func2({0x103760fa0, 0x1400057e450})
	/Users/bob/repos/trustification/guac/pkg/assembler/graphql/generated/artifact.generated.go:4685 +0xac
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query.func3({0x14000012be8?, 0x1033ff114?})
	/Users/bob/repos/trustification/guac/pkg/assembler/graphql/generated/artifact.generated.go:4689 +0x2c
github.com/99designs/gqlgen/graphql.(*FieldSet).Dispatch(0x1400029e190, {0x103760fa0?, 0x1400057e3f0?})
	/Users/bob/go/pkg/mod/github.com/99designs/gqlgen@v0.17.34/graphql/fieldset.go:41 +0xac
```

**GUAC version**

`main#HEAD` built locally.

**Additional context**

I'm an idiot, for one, and should've been certifying as a package, not an artifact.

**Comment by pxp928** [comment]
Additionally, need to add a check to `./bin/guacone certify -g artifact "approved by bob" 'pkg:rpm/redhat/acl@2.2.51-15.el7?arch=ppc64le'` such that it's an artifact type, it should not accept a purl and vise versa. This should be done for package, artifact, and source.

**Comment by lumjjb** [comment]
good catch @bobmcwhirter !
