### ISSUE TITLE
[bug] exactPackageName in keyvalue backend has incorrect condition for namespace

### ISSUE THREAD

**Issue by ridhoq** [guacsec/guac#1565]
**Describe the bug**
When calling [`exactPackageName`](https://github.com/guacsec/guac/blob/a4e806c3797c145d4916f59b2122c8a1a1bb56d1/pkg/assembler/backends/keyvalue/pkg.go#L921), the condition is checking for `filter.Namespace != nil` which is not correct since the logic is intended to only continue if all of three fields of `type`, `namespace`, and `name` are specified.

Found this issue when collecting SBOM with `keyvalue` backend and trying an `IsDependency` query without `namespace` specified gave the following stack trace:

```
guac-graphql-1       | runtime error: invalid memory address or nil pointer dereference
guac-graphql-1       | 
guac-graphql-1       | goroutine 528297 [running]:
guac-graphql-1       | runtime/debug.Stack()
guac-graphql-1       |  /home/ridwan/sdk/go1.21.3/src/runtime/debug/stack.go:24 +0x5e
guac-graphql-1       | runtime/debug.PrintStack()
guac-graphql-1       |  /home/ridwan/sdk/go1.21.3/src/runtime/debug/stack.go:16 +0x13
guac-graphql-1       | github.com/99designs/gqlgen/graphql.DefaultRecover({0x0?, 0xc007c76b40?}, {0x22d96c0?, 0x404c460?})
guac-graphql-1       |  /home/ridwan/go/pkg/mod/github.com/99designs/gqlgen@v0.17.39/graphql/recovery.go:17 +0x6b
guac-graphql-1       | github.com/99designs/gqlgen/graphql.(*OperationContext).Recover(0xc00367a320?, {0x2cc1cd0, 0xc040cf09c0}, {0x22d96c0?, 0x404c460?})
guac-graphql-1       |  /home/ridwan/go/pkg/mod/github.com/99designs/gqlgen@v0.17.39/graphql/context_operation.go:124 +0x38
guac-graphql-1       | github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query_IsDependency.func1()
guac-graphql-1       |  /home/ridwan/repos/github/ridhoq/guac/pkg/assembler/graphql/generated/artifact.generated.go:5528 +0x6e
guac-graphql-1       | panic({0x22d96c0?, 0x404c460?})
guac-graphql-1       |  /home/ridwan/sdk/go1.21.3/src/runtime/panic.go:914 +0x21f
guac-graphql-1       | github.com/guacsec/guac/pkg/assembler/backends/keyvalue.(*demoClient).exactPackageName(0x0?, {0x2cc1cd0, 0xc040cf09c0}, 0xc0002466e0)
guac-graphql-1       |  /home/ridwan/repos/github/ridhoq/guac/pkg/assembler/backends/keyvalue/pkg.go:929 +0x171
guac-graphql-1       | github.com/guacsec/guac/pkg/assembler/backends/keyvalue.(*demoClient).IsDependency(0xc0007895c0, {0x2cc1cd0, 0xc040cf09c0}, 0xc01d90eb00)
guac-graphql-1       |  /home/ridwan/repos/github/ridhoq/guac/pkg/assembler/backends/keyvalue/isDependency.go:181 +0x755
guac-graphql-1       | github.com/guacsec/guac/pkg/assembler/graphql/resolvers.(*queryResolver).IsDependency(0xc02eb4e048, {0x2cc1cd0, 0xc040cf09c0}, {0x0, 0x0, 0xc0002466e0, 0x0, 0x0, 0x0, 0x0, ...})
guac-graphql-1       |  /home/ridwan/repos/github/ridhoq/guac/pkg/assembler/graphql/resolvers/isDependency.resolvers.go:45 +0xab
guac-graphql-1       | github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query_IsDependency.func2({0x2cc1cd0?, 0xc040cf09c0})
guac-graphql-1       |  /home/ridwan/repos/github/ridhoq/guac/pkg/assembler/graphql/generated/artifact.generated.go:5534 +0x15c
guac-graphql-1       | github.com/99designs/gqlgen/graphql/executor.processExtensions.func4({0x2cc1cd0?, 0xc040cf09c0?}, 0xc0950921c0?)
guac-graphql-1       |  /home/ridwan/go/pkg/mod/github.com/99designs/gqlgen@v0.17.39/graphql/executor/extensions.go:72 +0x22
guac-graphql-1       | github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query_IsDependency(0xc0bdf1a160, {0x2cc1cd0, 0xc040cf0780}, {0xc0230b9c20, {0xc007c76a50, 0x1, 0x1}, 0x0})
guac-graphql-1       |  /home/ridwan/repos/github/ridhoq/guac/pkg/assembler/graphql/generated/artifact.generated.go:5532 +0x214
guac-graphql-1       | github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query.func40({0x2cc1cd0?, 0xc040cf0780?}, 0xc000246690)
guac-graphql-1       |  /home/ridwan/repos/github/ridhoq/guac/pkg/assembler/graphql/generated/artifact.generated.go:7422 +0xa5
guac-graphql-1       | github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query.func41.1({0x2cc1cd0?, 0xc040cf0780?})
guac-graphql-1       |  /home/ridwan/repos/github/ridhoq/guac/pkg/assembler/graphql/generated/artifact.generated.go:7431 +0x28
guac-graphql-1       | github.com/99designs/gqlgen/graphql/executor.processExtensions.func3({0x2cc1cd0?, 0xc040cf0780?}, 0x7f764b24f378?)
guac-graphql-1       |  /home/ridwan/go/pkg/mod/github.com/99designs/gqlgen@v0.17.39/graphql/executor/extensions.go:69 +0x22
guac-graphql-1       | github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query.func41({0x2cc1cd0, 0xc040cf0780})
guac-graphql-1       |  /home/ridwan/repos/github/ridhoq/guac/pkg/assembler/graphql/generated/artifact.generated.go:7430 +0xa2
guac-graphql-1       | github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query.func42({0x7f76926e3501?, 0x20?})
guac-graphql-1       |  /home/ridwan/repos/github/ridhoq/guac/pkg/assembler/graphql/generated/artifact.generated.go:7434 +0x22
guac-graphql-1       | github.com/99designs/gqlgen/graphql.(*FieldSet).Dispatch(0xc000246690, {0x2cc1cd0?, 0xc040cf0720?})
guac-graphql-1       |  /home/ridwan/go/pkg/mod/github.com/99designs/gqlgen@v0.17.39/graphql/fieldset.go:41 +0xa2
guac-graphql-1       | github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query(0xc0bdf1a160, {0x2cc1cd0, 0xc040cf06c0}, {0xc007c765c0, 0x1, 0x1})
guac-graphql-1       |  /home/ridwan/repos/github/ridhoq/guac/pkg/assembler/graphql/generated/artifact.generated.go:7755 +0x4ba5
guac-graphql-1       | github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executableSchema).Exec.func1({0x2cc1cd0, 0xc040cf0690})
guac-graphql-1       |  /home/ridwan/repos/github/ridhoq/guac/pkg/assembler/graphql/generated/root_.generated.go:2721 +0x234
guac-graphql-1       | github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1.1({0x2cc1cd0, 0xc040cf0690})
guac-graphql-1       |  /home/ridwan/go/pkg/mod/github.com/99designs/gqlgen@v0.17.39/graphql/executor/executor.go:120 +0x25
guac-graphql-1       | github.com/99designs/gqlgen/graphql/executor.processExtensions.func2({0x2cc1cd0?, 0xc040cf0690?}, 0x21d8fc0?)
guac-graphql-1       |  /home/ridwan/go/pkg/mod/github.com/99designs/gqlgen@v0.17.39/graphql/executor/extensions.go:66 +0x22
guac-graphql-1       | github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1({0x2cc1cd0, 0xc040cf05d0})
guac-graphql-1       |  /home/ridwan/go/pkg/mod/github.com/99designs/gqlgen@v0.17.39/graphql/executor/executor.go:119 +0x104
guac-graphql-1       | github.com/99designs/gqlgen/graphql/handler/transport.POST.Do({0x2cc1d08?}, {0x2cb5320?, 0xc0298e61c0}, 0xc06b268800, {0x2cb53e0, 0xc0007a3c20})
guac-graphql-1       |  /home/ridwan/go/pkg/mod/github.com/99designs/gqlgen@v0.17.39/graphql/handler/transport/http_post.go:91 +0x556
guac-graphql-1       | github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP(0xc000819960, {0x2cb5320, 0xc0298e61c0}, 0xc06b268800)
guac-graphql-1       |  /home/ridwan/go/pkg/mod/github.com/99designs/gqlgen@v0.17.39/graphql/handler/server.go:122 +0x278
guac-graphql-1       | net/http.(*ServeMux).ServeHTTP(0x4105a5?, {0x2cb5320, 0xc0298e61c0}, 0xc06b268100)
guac-graphql-1       |  /home/ridwan/sdk/go1.21.3/src/net/http/server.go:2514 +0x142
guac-graphql-1       | net/http.serverHandler.ServeHTTP({0x2cb0450?}, {0x2cb5320?, 0xc0298e61c0?}, 0x6?)
guac-graphql-1       |  /home/ridwan/sdk/go1.21.3/src/net/http/server.go:2938 +0x8e
guac-graphql-1       | net/http.(*conn).serve(0xc0230b8750, {0x2cc1cd0, 0xc0001982a0})
guac-graphql-1       |  /home/ridwan/sdk/go1.21.3/src/net/http/server.go:2009 +0x5f4
guac-graphql-1       | created by net/http.(*Server).Serve in goroutine 16
guac-graphql-1       |  /home/ridwan/sdk/go1.21.3/src/net/http/server.go:3086 +0x5cb
```

**To Reproduce**

1. Collect SBOM against default backend GQL server
2. Run a query like this without `namespace` specified:

```graphql
query IsDependencyQ2 {
  IsDependency(
    isDependencySpec: {dependencyPackage: {type: "npm", name: "pkgname"}}
  ) {
    package {
      ...allPkgTree
    }
  }
}
```
3. See that `internal server error` is thrown and that stack trace appears in `guacgql` server logs

**Expected behavior**
No error is thrown

**GUAC version**
Latest on main

**Additional context**
Thanks to @jeffmendoza for helping to isolate the bug

**Comment by ridhoq** [comment]
Closed by #1627
