### ISSUE TITLE
[bug] Graphql Shutting Down When Running Query

### ISSUE THREAD

**Issue by nathannaveen** [guacsec/guac#1617]
**Describe the bug**

When I run the following query `IsDependencyQ2 ` in the graphql playground I get the error `"internal system error”`.

```
fragment allIsDependencyTree on IsDependency {
  id
  justification
  package {
    id
    type
    namespaces {
      id
      namespace
      names {
        id
        name
        versions {
          id
          version
          qualifiers {
            key
            value
          }
          subpath
        }
      }
    }
  }
  dependencyPackage {
    id
    type
    namespaces {
      id
      namespace
      names {
        id
        name
        versions {
          id
          version
          qualifiers {
            key
            value
          }
          subpath
        }
      }
    }
  }
  dependencyType
  versionRange
  origin
  collector
}

query IsDependencyQ1 {
  IsDependency(isDependencySpec: {
    dependencyPackage: {
      id: 1006
    }
  }) {
    ...allIsDependencyTree
  }
}

query IsDependencyQ2 {
  IsDependency(isDependencySpec: {
    dependencyPackage: {
      type: "golang"
      name: "net"
    }
  }) {
    ...allIsDependencyTree
  }
}
```

When ever I run `IsDependencyQ2` my graphql shuts down. If I run any other type of query, like `IsDependencyQ1` then it doesn’t quit.

**Screenshots**

What I am getting when the graphql shuts down:

```
➜  guac git:(main) go run ./cmd/guacgql --gql-debug
{"level":"info","ts":1703714313.5010402,"caller":"logging/logger.go:70","msg":"Logging at info level"}
{"level":"info","ts":1703714313.5012429,"caller":"cli/init.go:67","msg":"Using config file: /Users/nathannaveen/go/src/github.com/nathannaveen/guac/guac.yaml"}
{"level":"info","ts":1703714313.5014,"caller":"cmd/server.go:97","msg":"connect to http://localhost:8080/ for GraphQL playground"}
{"level":"info","ts":1703714313.5014532,"caller":"cmd/server.go:101","msg":"starting server"}
runtime error: invalid memory address or nil pointer dereference

goroutine 774453 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/debug/stack.go:16 +0x1c
github.com/99designs/gqlgen/graphql.DefaultRecover({0x1f?, 0x16?}, {0x105e6bae0?, 0x106f76670?})
	/Users/nathannaveen/go/pkg/mod/github.com/99designs/gqlgen@v0.17.41/graphql/recovery.go:17 +0x70
github.com/99designs/gqlgen/graphql.(*OperationContext).Recover(0x14000762238?, {0x1060bc8f8, 0x140045daab0}, {0x105e6bae0?, 0x106f76670?})
	/Users/nathannaveen/go/pkg/mod/github.com/99designs/gqlgen@v0.17.41/graphql/context_operation.go:124 +0x44
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query_IsDependency.func1()
	/Users/nathannaveen/go/src/github.com/nathannaveen/guac/pkg/assembler/graphql/generated/artifact.generated.go:5540 +0x68
panic({0x105e6bae0?, 0x106f76670?})
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/panic.go:914 +0x218
github.com/guacsec/guac/pkg/assembler/backends/keyvalue.(*demoClient).exactPackageName(0x1056b002d?, {0x1060bc8f8, 0x140045daab0}, 0x140025a32c0)
	/Users/nathannaveen/go/src/github.com/nathannaveen/guac/pkg/assembler/backends/keyvalue/pkg.go:962 +0x140
github.com/guacsec/guac/pkg/assembler/backends/keyvalue.(*demoClient).IsDependency(0x14000016960, {0x1060bc8f8, 0x140045daab0}, 0x14010b97bc0)
	/Users/nathannaveen/go/src/github.com/nathannaveen/guac/pkg/assembler/backends/keyvalue/isDependency.go:182 +0x580
github.com/guacsec/guac/pkg/assembler/graphql/resolvers.(*queryResolver).IsDependency(0x1400438c9a8, {0x1060bc8f8, 0x140045daab0}, {0x0, 0x0, 0x140025a32c0, 0x0, 0x0, 0x0, 0x0, ...})
	/Users/nathannaveen/go/src/github.com/nathannaveen/guac/pkg/assembler/graphql/resolvers/isDependency.resolvers.go:35 +0xc0
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query_IsDependency.func2({0x1060bc8f8?, 0x140045daab0})
	/Users/nathannaveen/go/src/github.com/nathannaveen/guac/pkg/assembler/graphql/generated/artifact.generated.go:5546 +0x120
github.com/99designs/gqlgen/graphql/executor.processExtensions.func4({0x1060bc8f8?, 0x140045daab0?}, 0x140043809a0?)
	/Users/nathannaveen/go/pkg/mod/github.com/99designs/gqlgen@v0.17.41/graphql/executor/extensions.go:72 +0x2c
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query_IsDependency(0x14001f87400, {0x1060bc8f8, 0x140045da870}, {0x140043979e0, {0x14004f129d0, 0x1, 0x1}, 0x0})
	/Users/nathannaveen/go/src/github.com/nathannaveen/guac/pkg/assembler/graphql/generated/artifact.generated.go:5544 +0x1a4
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query.func40({0x1060bc8f8?, 0x140045da870?}, 0x140025a3270)
	/Users/nathannaveen/go/src/github.com/nathannaveen/guac/pkg/assembler/graphql/generated/artifact.generated.go:7424 +0x94
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query.func41.1({0x1060bc8f8?, 0x140045da870?})
	/Users/nathannaveen/go/src/github.com/nathannaveen/guac/pkg/assembler/graphql/generated/artifact.generated.go:7433 +0x34
github.com/99designs/gqlgen/graphql/executor.processExtensions.func3({0x1060bc8f8?, 0x140045da870?}, 0x10?)
	/Users/nathannaveen/go/pkg/mod/github.com/99designs/gqlgen@v0.17.41/graphql/executor/extensions.go:69 +0x2c
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query.func41({0x1060bc8f8, 0x140045da870})
	/Users/nathannaveen/go/src/github.com/nathannaveen/guac/pkg/assembler/graphql/generated/artifact.generated.go:7432 +0xa4
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query.func42({0x14000762bb8?, 0x105452d0c?})
	/Users/nathannaveen/go/src/github.com/nathannaveen/guac/pkg/assembler/graphql/generated/artifact.generated.go:7436 +0x30
github.com/99designs/gqlgen/graphql.(*FieldSet).Dispatch(0x140025a3270, {0x1060bc8f8?, 0x140045da810?})
	/Users/nathannaveen/go/pkg/mod/github.com/99designs/gqlgen@v0.17.41/graphql/fieldset.go:41 +0xa8
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query(0x14001f87400, {0x1060bc8f8, 0x140045da7b0}, {0x14008387b90, 0x1, 0x1})
	/Users/nathannaveen/go/src/github.com/nathannaveen/guac/pkg/assembler/graphql/generated/artifact.generated.go:7757 +0x4640
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executableSchema).Exec.func1({0x1060bc8f8, 0x140045da780})
	/Users/nathannaveen/go/src/github.com/nathannaveen/guac/pkg/assembler/graphql/generated/root_.generated.go:2740 +0x1fc
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1.1({0x1060bc8f8, 0x140045da780})
	/Users/nathannaveen/go/pkg/mod/github.com/99designs/gqlgen@v0.17.41/graphql/executor/executor.go:120 +0x2c
github.com/99designs/gqlgen/graphql/executor.processExtensions.func2({0x1060bc8f8?, 0x140045da780?}, 0x105d9b660?)
	/Users/nathannaveen/go/pkg/mod/github.com/99designs/gqlgen@v0.17.41/graphql/executor/extensions.go:66 +0x2c
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1({0x1060bc8f8, 0x140045da6c0})
	/Users/nathannaveen/go/pkg/mod/github.com/99designs/gqlgen@v0.17.41/graphql/executor/executor.go:119 +0x108
github.com/99designs/gqlgen/graphql/handler/transport.POST.Do({0x1060bc930?}, {0x1060b9440?, 0x1400338e000}, 0x14005b46100, {0x1060b9500, 0x140006b6280})
	/Users/nathannaveen/go/pkg/mod/github.com/99designs/gqlgen@v0.17.41/graphql/handler/transport/http_post.go:91 +0x45c
github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP(0x1400071b080, {0x1060b9440, 0x1400338e000}, 0x14005b46100)
	/Users/nathannaveen/go/pkg/mod/github.com/99designs/gqlgen@v0.17.41/graphql/handler/server.go:122 +0x1fc
net/http.(*ServeMux).ServeHTTP(0x10?, {0x1060b9440, 0x1400338e000}, 0x14005b46000)
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/net/http/server.go:2514 +0x144
net/http.serverHandler.ServeHTTP({0x1060b51c8?}, {0x1060b9440?, 0x1400338e000?}, 0x6?)
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/net/http/server.go:2938 +0xbc
net/http.(*conn).serve(0x14004396000, {0x1060bc8f8, 0x1400002c1b0})
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/net/http/server.go:2009 +0x518
created by net/http.(*Server).Serve in goroutine 7
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/net/http/server.go:3086 +0x4cc
```
**GUAC version**
Guac v0.3.0

**Comment by jeffmendoza** [comment]
Looking at the stacktrace, looks like this is related to #1565 / #1606 

When doing the backedge searching for verb queries, if the verb can be connected to either pkg-name or pkg-version the logic skips the backedge search most of the time.

For IsDep, it used to be only pkg-version for the pkg and pkg-name for the depPkg, so it would do the backedge search. I believe it is still trying the backedge search for depPkg, but is probably not correct somewhere.

To be like other verbs, we could remove the backedge search on depPkg for IsDep, OR we could figure out how to do the backedge search correctly on queries for verbs that have fields that can link to either pkg-name or pkg-version.

**Comment by lumjjb** [comment]
Hi @nathannaveen it looks like some fixes have been merged, can you see if you can reproduce this again?

**Comment by nathannaveen** [comment]
Yes, the bug is fixed, I just forgot to close the issue.
