### ISSUE TITLE
[ingestion bug] Ingesting this specific CDX SBOM will cause a panic

### ISSUE THREAD

**Issue by nchelluri** [guacsec/guac#2048]
**Describe the bug**

If I try to ingest https://github.com/chainguard-dev/bom-shelter/blob/89ed4943e027c9bf148e6a80d7b2b78ae8d7771a/in-the-wild/cyclonedx/ascii-boxes-sbom-cdx.json then I will get a `panic: runtime error: invalid memory address or nil pointer dereference`. This seems to happen with both `guacone collect files` and with `guacingest` getting data from `guaccollect files` and NATS and a  local blob store.

**To Reproduce**

1. Download the SBOM
2. Run `go run ./cmd/guacone collect files ~/scratch/ascii-boxes-sbom-cdx.json`
3. See error

**Expected behavior**
There is no panic.

**GUAC version**
v0.8.0 - I have 0c6dc86ff3ab98e9572d5c936160c75e84d7c4df checked out

**Ingested document(s)**
[ascii-boxes-sbom-cdx.json](https://github.com/user-attachments/files/16394544/ascii-boxes-sbom-cdx.json)

**Additional context**
Full output of this command:

```
nchelluri@Narsimhams-MBP guac % go run ./cmd/guacone collect files ~/scratch/ascii-boxes-sbom-cdx.json                          main
{"level":"info","ts":1722012253.780885,"caller":"logging/logger.go:78","msg":"Logging at info level","guac-version":"v0.0.1-custom"}
{"level":"info","ts":1722012253.780988,"caller":"cli/init.go:65","msg":"Using config file: /Users/nchelluri/dev/guac/guac.yaml","guac-version":"v0.0.1-custom"}
{"level":"info","ts":1722012253.7813041,"caller":"process/process.go:282","msg":"Decoding document with encoding:  ","guac-version":"v0.0.1-custom"}
{"level":"info","ts":1722012253.782412,"caller":"parser/parser.go:83","msg":"parsing document tree with root type: CycloneDX","guac-version":"v0.0.1-custom","documentHash":"sha256_87424b073c43b67ed7b038ce2eebe09be670c36f73fd041464fd0d037bf027e8"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x10495afa0]

goroutine 1 [running]:
github.com/guacsec/guac/pkg/ingestor/parser/cyclonedx.getLicenseFromName(0x3?, {0x0?, {0x14000e0c520?, 0x14000b916ca?}})
	/Users/nchelluri/dev/guac/pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go:306 +0x20
github.com/guacsec/guac/pkg/ingestor/parser/cyclonedx.(*cyclonedxParser).getLicenseInformation(_, {{0x0, 0x0}, {0x0, 0x0}, {0x14000e0c4d0, 0x7}, 0x0, 0x0, {0x14000b91650, ...}, ...})
	/Users/nchelluri/dev/guac/pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go:287 +0x374
github.com/guacsec/guac/pkg/ingestor/parser/cyclonedx.(*cyclonedxParser).getPackages(0x14000826aa0)
	/Users/nchelluri/dev/guac/pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go:247 +0x33c
github.com/guacsec/guac/pkg/ingestor/parser/cyclonedx.(*cyclonedxParser).Parse(0x14000826aa0, {0x105c8dea0, 0x1400082eba0}, 0x1400079b500)
	/Users/nchelluri/dev/guac/pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go:107 +0xe4
github.com/guacsec/guac/pkg/ingestor/parser.parseHelper({0x105c8dea0, 0x1400082eba0}, 0x1400079b500)
	/Users/nchelluri/dev/guac/pkg/ingestor/parser/parser.go:179 +0x7c
github.com/guacsec/guac/pkg/ingestor/parser.(*docTreeBuilder).parse(0x14000d233f0, {0x105c8dea0, 0x1400082eba0}, 0x140007a9840, 0x14000d233c0)
	/Users/nchelluri/dev/guac/pkg/ingestor/parser/parser.go:150 +0x44
github.com/guacsec/guac/pkg/ingestor/parser.ParseDocumentTree({0x105c8dea0, 0x1400082eba0}, 0x140007a9840, 0x0, 0x0)
	/Users/nchelluri/dev/guac/pkg/ingestor/parser/parser.go:84 +0x120
github.com/guacsec/guac/pkg/ingestor.Ingest.GetIngestor.func2(...)
	/Users/nchelluri/dev/guac/pkg/ingestor/ingestor.go:168
github.com/guacsec/guac/pkg/ingestor.Ingest({0x105c8dea0, 0x1400082eba0}, 0x1400079b500, {0x14000510cc0, 0x1b}, {0x105c66958, 0x1073031e0}, {0x105c88ca8?, 0x14000982708?}, 0x0, ...)
	/Users/nchelluri/dev/guac/pkg/ingestor/ingestor.go:62 +0x29c
github.com/guacsec/guac/cmd/guacone/cmd.init.func7.1(0x1400079b500)
	/Users/nchelluri/dev/guac/cmd/guacone/cmd/files.go:132 +0x7c
github.com/guacsec/guac/pkg/handler/collector.Collect({0x105c8dea0, 0x1400082eba0}, 0x14000d23b70, 0x14000d23b60)
	/Users/nchelluri/dev/guac/pkg/handler/collector/collector.go:107 +0x2ac
github.com/guacsec/guac/cmd/guacone/cmd.init.func7(0x10730be00, {0x14000714430, 0x1, 0x1})
	/Users/nchelluri/dev/guac/cmd/guacone/cmd/files.go:151 +0x704
github.com/spf13/cobra.(*Command).execute(0x10730be00, {0x140007143f0, 0x1, 0x1})
	/Users/nchelluri/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x10730d500)
	/Users/nchelluri/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/nchelluri/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/guacsec/guac/cmd/guacone/cmd.Execute()
	/Users/nchelluri/dev/guac/cmd/guacone/cmd/root.go:57 +0x24
main.main()
	/Users/nchelluri/dev/guac/cmd/guacone/main.go:23 +0x1c
exit status 2
```

Based on a quick inspection it appears that `compLicense.License == nil ` in `getLicenseFromName()` in `pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go`.

**Comment by pxp928** [comment]
Hmm is this valid per the cyclone DX spec?

```
    "components": [
        {
            "type": "library",
            "author": "Ben Pfaff, Bruno Haible, and Daiki Ueno",
            "name": "libunistring",
            "version": "0.9.10-4",
            "description": "Functions for manipulating Unicode strings and for manipulating C strings according to the Unicode standard",
            "licenses": [
                {
                    "expression": "GPL-3.0-or-later"
                },
                {
                    "expression": "GPL-2.0-only"
                }
            ],
            "externalReferences": [
                {
                    "type": "website",
                    "url": "https://www.gnu.org/software/libunistring/"
                }
            ],
            "properties": [
                {
                    "name": "primaryLanguage",
                    "value": "C"
                }
            ]
        },
```

https://cyclonedx.org/docs/1.6/json/#tab-pane_components_items_licenses_oneOf_i1

Based on the spec:
EITHER (list of SPDX licenses and/or named licenses) OR (tuple of one SPDX License Expression)

So there should not be multiple license expressions correct?

**Comment by pxp928** [comment]
Based on discussion, this looks to be an older version of CDX: https://cyclonedx.org/docs/1.4/json/#tab-pane_components_items_licenses_items_oneOf_i0

Where multiple expressions are allowed. Question is, do we want to support multiple versions of CDX or the latest?

Thoughts from others? @lumjjb, @SantiagoTorres, @mihaimaruseac, @jeffmendoza, @mlieberman85

**Comment by mlieberman85** [comment]
I would say hold off until someone comes with a ton of older CDX SBOMs.

**Comment by mihaimaruseac** [comment]
+1 to what Mike says. If it's a one off case it doesn't make sense to over complicate.

**Comment by nchelluri** [comment]
Fixing the issue of supporting multiple specs is one thing and punting seems fine. But, I do think the panic should be addressed (I don’t think guac should ever panic)

**Comment by pxp928** [comment]
agreed, created PR to ensure that it does not panic.

**Comment by mihaimaruseac** [comment]
Oh, definitely agreed with removing the panic.
