### ISSUE TITLE
slsa type panics with index out of range

### ISSUE THREAD

**Issue by lukehinds** [guacsec/guac#235]
```
go run cmd/guacone/main.go files --creds neo4j:s3cr3t /Users/lhinds/go/src/github.com/guacsec/guac-data/docs/slsa/kube-slsa-v1.24.4.json
```

Result:

```
Edge count: 339
Edge value: {{gs://kubernetes-release/release/v1.24.4/bin/linux/ppc64le/kubeadm sha512:3ac32a1f65470c5f336e6d9886ad2f544afae9787dc58b527b8d637f00c4a4ff39c5e1e89f147becb7dc48bebae020b583e48d0f5a69610f5021221f36de8ddb} {https://cloudbuild.googleapis.com/CloudBuildYaml@v1 https://git.k8s.io/release/docs/krel}}
Edge count: 340
Edge value: {{file:////Users/lhinds/go/src/github.com/guacsec/guac-data/docs/slsa/kube-slsa-v1.24.4.json sha256:5359ddbe12ea96f99192760aded254dac8c606cd3c11340bf095d5c08dc95a83} {gs://kubernetes-release/release/v1.24.4/bin/linux/ppc64le/kubeadm sha512:3ac32a1f65470c5f336e6d9886ad2f544afae9787dc58b527b8d637f00c4a4ff39c5e1e89f147becb7dc48bebae020b583e48d0f5a69610f5021221f36de8ddb}}
Edge count: 341
Edge value: {{gs://kubernetes-release/release/v1.24.4/bin/linux/ppc64le/kubeadm sha512:3ac32a1f65470c5f336e6d9886ad2f544afae9787dc58b527b8d637f00c4a4ff39c5e1e89f147becb7dc48bebae020b583e48d0f5a69610f5021221f36de8ddb} {git+https://github.com/kubernetes/kubernetes sha1:'252935368ab67f38cb252df0a961a6dcb81d20eb'}}
Edge count: 342
Edge value: {{gs://kubernetes-release/release/v1.24.4/kubernetes-client-darwin-amd64.tar.gz sha512:592715dd609e48392e9228979c85819507dd7f62cfcba16eecaea33e607de0c6f5bfa437299fd38b4848c41415bc8ce7f04078dfc91d99e9d7b5a0dde314455f} {https://cloudbuild.googleapis.com/CloudBuildYaml@v1 https://git.k8s.io/release/docs/krel}}
panic: runtime error: index out of range [342] with length 342

goroutine 1 [running]:
github.com/guacsec/guac/pkg/assembler.StoreGraph({{0x14000184800, 0x156, 0x180}, {0x1400040c000, 0x3f9, 0x400}}, {0x102f18580?, 0x14000166e70?})
	/Users/lhinds/go/src/github.com/guacsec/guac/pkg/assembler/graphdb.go:66 +0x898
github.com/guacsec/guac/cmd/guacone/cmd.getAssembler.func1({0x140003bc930?, 0x1?, 0x1400024fa6c?})
	/Users/lhinds/go/src/github.com/guacsec/guac/cmd/guacone/cmd/files.go:178 +0x84
github.com/guacsec/guac/cmd/guacone/cmd.glob..func1.1(0x1400012f140)
	/Users/lhinds/go/src/github.com/guacsec/guac/cmd/guacone/cmd/files.go:109 +0x11c
github.com/guacsec/guac/pkg/handler/collector.Collect({0x102f17960?, 0x14000259860}, 0x14000331ca8, 0x14000331c38)
	/Users/lhinds/go/src/github.com/guacsec/guac/pkg/handler/collector/collector.go:84 +0x274
github.com/guacsec/guac/cmd/guacone/cmd.glob..func1(0x1032a1160?, {0x14000259800, 0x1, 0x3})
	/Users/lhinds/go/src/github.com/guacsec/guac/cmd/guacone/cmd/files.go:125 +0x430
github.com/spf13/cobra.(*Command).execute(0x1032a1160, {0x140002597a0, 0x3, 0x3})
	/Users/lhinds/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x4b8
github.com/spf13/cobra.(*Command).ExecuteC(0x1032a13e0)
	/Users/lhinds/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/lhinds/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/guacsec/guac/cmd/guacone/cmd.Execute()
	/Users/lhinds/go/src/github.com/guacsec/guac/cmd/guacone/cmd/root.go:35 +0x28
main.main()
	/Users/lhinds/go/src/github.com/guacsec/guac/cmd/guacone/main.go:23 +0x1c
exit status 2
```

**Comment by lumjjb** [comment]
Hey @lukehinds ! Can you share the SLSA document that you used for ingestion? Thanks! We'll look into it!

**Comment by lumjjb** [comment]
ahh, didn't see the file name 😂 ! oh heh, that's weird, I'll take a look

**Comment by lumjjb** [comment]
Line 66 seems to point to this, which seems like it shouldn't panic. The only thing that comes up that reminds me of this behavior is the fix for https://github.com/guacsec/guac/commit/dd39412ff09ee968321c28a6b3ae51e4fdea8292

```
 66         for k, v := range b.Properties() {
```

Noticed you had a few other pieces of output, would you be able to do a `git diff` from main and share that - and we can test with the diff.

**Comment by lukehinds** [comment]
I just had some fmt.printlins in to help debug, this is the result with no staged changes right off main:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/7058938/202520707-2998ba05-ed3d-466a-a6d0-1b10df016822.png">

Could this be an apple silicon thing?

**Comment by lumjjb** [comment]
hmm, it looks like HEAD seems to be pointing to an old commit on 27 sep. Believe it should be pointing to e6319dbd5b22d9b9520471d64a8636a043c7253a

**Comment by lukehinds** [comment]
gah! I was working off a fork, sorry for the noise!
