### ISSUE TITLE
[ingestion/data-quality issue] Error when ingesting SBOM from JFrog Xray

### ISSUE THREAD

**Issue by M-Polonczyk** [guacsec/guac#2369]
**Describe the bug**
When I am importing (using guacone collect files command) SBOM in CycloneDX format - it gives me an error:

```
$ guacone collect files SBOM_CycloneDX.json 
{"level":"info","ts":1733912230.6325142,"caller":"logging/logger.go:79","msg":"Logging at info level","guac-version":"v0.11.2"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2625b73]

goroutine 1 [running]:
github.com/guacsec/guac/pkg/ingestor/parser/cyclonedx.(*cyclonedxParser).getVulnerabilities(0xc00095c5a0, {0x3c14bb8, 0xc0013bf470})
        /home/runner/work/guac/guac/pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go:600 +0x3f3
github.com/guacsec/guac/pkg/ingestor/parser/cyclonedx.(*cyclonedxParser).Parse(0xc00095c5a0, {0x3c14bb8, 0xc0013bf470}, 0xc0012c5580)
        /home/runner/work/guac/guac/pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go:113 +0x1c5
github.com/guacsec/guac/pkg/ingestor/parser.parseHelper({0x3c14bb8, 0xc0013bf470}, 0xc0012c5580)
        /home/runner/work/guac/guac/pkg/ingestor/parser/parser.go:191 +0x7d
github.com/guacsec/guac/pkg/ingestor/parser.(*docTreeBuilder).parse(0xc0015613f0, {0x3c14bb8, 0xc0013bf470}, 0xc000b960a0, 0xc0015613b0)
        /home/runner/work/guac/guac/pkg/ingestor/parser/parser.go:162 +0x53
github.com/guacsec/guac/pkg/ingestor/parser.ParseDocumentTree({0x3c14bb8, 0xc0013bf470}, 0xc000b960a0, 0x0, 0x0)
        /home/runner/work/guac/guac/pkg/ingestor/parser/parser.go:87 +0x1a6
github.com/guacsec/guac/pkg/ingestor.Ingest.GetIngestor.func2(...)
        /home/runner/work/guac/guac/pkg/ingestor/ingestor.go:169
github.com/guacsec/guac/pkg/ingestor.Ingest({0x3c14bb8, 0xc0013bf470}, 0xc0012c5580, {0x3373e6f, 0x1b}, {0x3bd7c60, 0x5925ec0}, {0x3c0f320?, 0xc000b9d290?}, 0x0, ...)
        /home/runner/work/guac/guac/pkg/ingestor/ingestor.go:62 +0x390
github.com/guacsec/guac/cmd/guacone/cmd.init.func7.1(0xc0012c5580)
        /home/runner/work/guac/guac/cmd/guacone/cmd/files.go:132 +0x9f
github.com/guacsec/guac/pkg/handler/collector.Collect({0x3c14bb8, 0xc0013bf470}, 0xc001561b90, 0xc001561b80)
        /home/runner/work/guac/guac/pkg/handler/collector/collector.go:107 +0x3ae
github.com/guacsec/guac/cmd/guacone/cmd.init.func7(0x5931900, {0xc00165eca0, 0x1, 0x1})
        /home/runner/work/guac/guac/cmd/guacone/cmd/files.go:151 +0x938
github.com/spf13/cobra.(*Command).execute(0x5931900, {0xc00165ec60, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x59332e0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/guacsec/guac/cmd/guacone/cmd.Execute()
        /home/runner/work/guac/guac/cmd/guacone/cmd/root.go:57 +0x1a
main.main()
        /home/runner/work/guac/guac/cmd/guacone/main.go:23 +0xf
```
It works only after excluding vulnerabilities when exporting.
![sbom_export](https://github.com/user-attachments/assets/27686058-3075-42c5-b60d-648f540439d6)

When I import the same one in SPDX - it works (gets a warning from spdx/parse_spdx.go:285 about top-level packages and artifacts being mismatched), however GraphQL doesn't return any information about vulnerabilities, when this SBOM has about 60 of them. 
Warning which may be related to this issue:
```
$ guacone collect files --add-vuln-on-ingest Docker_Maven_SBOM_SPDX.json 
{"level":"info","ts":1733922966.2145932,"caller":"logging/logger.go:79","msg":"Logging at info level","guac-version":"v0.11.2"}
{"level":"warn","ts":1733922966.4876654,"caller":"spdx/parse_spdx.go:285","msg":"Top-level unique artifact count (265) and top-level package count (271) are mismatched. SBOM ingestion may not be as expected.","guac-version":"v0.11.2"}
```
Unfortunately I cannot share SBOM related with this problem.

**To Reproduce**

1. Export SBOM from scanned package/artifact
2. Start GUAC with Postgres database using Docker Compose
3. Ingest SBOM using `guacone collect files` or `guacone collect files --add-vuln-on-ingest`

**Expected behavior**
Information about packages via GraphQL API. Some times vulnerabilities missing

**GUAC version**
Installed 2 weeks ago. Logs tells it's `v0.11.2`

**Ingested document(s)**

SPDX
[Docker_Maven_SBOM_SPDX.json](https://github.com/user-attachments/files/18149777/Docker_Maven_SBOM_SPDX.json)

CycloneDX (no vulns)
[Docker_Maven_SBOM_CycloneDX_novulns.json](https://github.com/user-attachments/files/18149779/Docker_Maven_SBOM_CycloneDX_novulns.json)

CycloneDX (vulns)
[Docker_Maven_SBOM_CycloneDX.json](https://github.com/user-attachments/files/18149781/Docker_Maven_SBOM_CycloneDX.json)

**Comment by lumjjb** [comment]
The SPDX warning looks fine, that's just saying that there's a difference in the top level unique packages and the list of packages, which is fine as long as all expected packages are there.
